echo Stopping Nginx...
taskkill /F /IM nginx.exe > nul
echo Stopping PHP FastCGI...
taskkill /F /IM php-cgi.exe > nul
echo Stopping Redis...  
taskkill /F /IM redis-server.exe > nul  
echo Stopping Memcached...  
taskkill /F /IM memcached.exe > nul  
